//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace POPPING_PARADISE成员管理系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public member()
        {
            this.attendance = new HashSet<attendance>();
            this.evaluation = new HashSet<evaluation>();
            this.skill = new HashSet<skill>();
            this.stage = new HashSet<stage>();
        }
    
        public int mId { get; set; }
        public string 姓名 { get; set; }
        public string 用户名 { get; set; }
        public string 密码 { get; set; }
        public string 性别 { get; set; }
        public string 学院 { get; set; }
        public string 班级 { get; set; }
        public string 职务 { get; set; }
        public string 电话 { get; set; }
        public string 邮箱 { get; set; }
        public Nullable<int> 等级 { get; set; }
        public string 爱好 { get; set; }
        public string 座右铭 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendance> attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evaluation> evaluation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skill> skill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stage> stage { get; set; }
    }
}
