//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace POPPING_PARADISE成员管理系统
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myDBEntities : DbContext
    {
        public myDBEntities()
            : base("name=myDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attendance> attendance { get; set; }
        public virtual DbSet<evaluation> evaluation { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<skill> skill { get; set; }
        public virtual DbSet<stage> stage { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
