//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace POPPING_PARADISE成员管理系统
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        public int skId { get; set; }
        public string 元素名称 { get; set; }
        public string 元素简介 { get; set; }
        public string 视频 { get; set; }
        public Nullable<int> 元素掌握人员 { get; set; }
    
        public virtual member member { get; set; }
    }
}
